export PYTHONPATH=${PYTHONPATH}:$(pwd)/exploChallenge:$(pwd)/myPolicy
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py
python2.7 exploChallenge/Main.py