perl outputSummaryStats.pl
perl processSummaryStats.pl
perl outputEnsembleProportionSummaryStats.pl

perl processEnsembleProportionSummaryStats.pl EnsembleRandom
perl processEnsembleProportionSummaryStats.pl EnsembleRandomUpdateAll
perl processEnsembleProportionSummaryStats.pl EnsembleEAnnealing
perl processEnsembleProportionSummaryStats.pl EnsembleSoftmax0.01
perl processEnsembleProportionSummaryStats.pl EnsembleBayesian
perl processEnsembleProportionSummaryStats.pl EnsembleBinomialUCI
perl processEnsembleProportionSummaryStats.pl EnsembleBinomialUCIMod1
perl processEnsembleProportionSummaryStats.pl EnsembleBinomialUCIMod2

python create_mean_aer_plot.py
python create_mean_aer_plot_contextual.py
python create_mean_aer_plot_ensemble.py
python create_min_aer_plot.py
python create_min_aer_plot_contextual.py
python create_min_aer_plot_ensemble.py
python create_max_aer_plot.py
python create_max_aer_plot_contextual.py
python create_max_aer_plot_ensemble.py
python create_delta_aer_plot.py
python create_delta_aer_plot_contextual.py
python create_delta_aer_plot_ensemble.py
python create_stdev_aer_plot.py
python create_stdev_aer_plot_contextual.py
python create_stdev_aer_plot_ensemble.py
python create_runtime_plot.py
python create_runtime_plot_contextual.py
python create_runtime_plot_ensemble.py
python create_mean_aer_vs_time_plot.py
python create_mean_aer_vs_time_plot_contextual.py
python create_mean_aer_vs_time_plot_ensemble.py
python create_mean_aer_plot_with_ranges.py
python create_aer_proportion_of_optimal_ensemble_plot.py
python create_aer_proportion_of_optimal_vs_time_ensemble_plot.py

python create_mean_ensemble_bandit_proportions_plot.py EnsembleRandom
python create_mean_ensemble_bandit_proportions_plot.py EnsembleRandomUpdateAll
python create_mean_ensemble_bandit_proportions_plot.py EnsembleEAnnealing
python create_mean_ensemble_bandit_proportions_plot.py EnsembleSoftmax0.01
python create_mean_ensemble_bandit_proportions_plot.py EnsembleBayesian
python create_mean_ensemble_bandit_proportions_plot.py EnsembleBinomialUCI
python create_mean_ensemble_bandit_proportions_plot.py EnsembleBinomialUCIMod1
python create_mean_ensemble_bandit_proportions_plot.py EnsembleBinomialUCIMod2

python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleRandom
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleRandomUpdateAll
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleEAnnealing
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleSoftmax0.01
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBayesian
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBinomialUCI
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBinomialUCIMod1
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBinomialUCIMod2