perl outputSummaryStats.pl
perl processSummaryStats.pl
perl outputEnsembleProportionSummaryStats.pl

perl processEnsembleProportionSummaryStats.pl EnsembleRandom
perl processEnsembleProportionSummaryStats.pl EnsembleRandomUpdateAll
perl processEnsembleProportionSummaryStats.pl EnsembleEAnnealingUpdateAll
perl processEnsembleProportionSummaryStats.pl EnsembleSoftmax0.01UpdateAll
#perl processEnsembleProportionSummaryStats.pl EnsembleBayesianUpdateALl
perl processEnsembleProportionSummaryStats.pl EnsembleBinomialUCIUpdateAll
#perl processEnsembleProportionSummaryStats.pl EnsembleBinomialUCIMod1UpdateAll

python create_mean_aer_plot.py
python create_mean_aer_plot_contextual.py
python create_mean_aer_plot_ensemble.py
python create_min_aer_plot.py
python create_min_aer_plot_contextual.py
python create_min_aer_plot_ensemble.py
python create_max_aer_plot.py
python create_max_aer_plot_contextual.py
python create_max_aer_plot_ensemble.py
python create_stdev_aer_plot.py
python create_stdev_aer_plot_contextual.py
python create_stdev_aer_plot_ensemble.py
python create_runtime_plot.py
python create_runtime_plot_contextual.py
#python create_runtime_plot_ensemble.py
python create_mean_aer_vs_time_plot.py
python create_mean_aer_vs_time_plot_contextual.py
python create_mean_aer_vs_time_plot_ensemble.py
python create_mean_aer_plot_with_ranges.py
python create_aer_proportion_of_optimal_ensemble_plot.py
python create_aer_proportion_of_optimal_vs_time_ensemble_plot.py

python create_mean_ensemble_bandit_proportions_plot.py EnsembleRandom
python create_mean_ensemble_bandit_proportions_plot.py EnsembleRandomUpdateAll
python create_mean_ensemble_bandit_proportions_plot.py EnsembleEAnnealingUpdateAll
python create_mean_ensemble_bandit_proportions_plot.py EnsembleSoftmax0.01UpdateAll
#python create_mean_ensemble_bandit_proportions_plot.py EnsembleBayesianUpdateALl
python create_mean_ensemble_bandit_proportions_plot.py EnsembleBinomialUCIUpdateAll
#python create_mean_ensemble_bandit_proportions_plot.py EnsembleBinomialUCIMod1UpdateAll

python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleRandom
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleRandomUpdateAll
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleEAnnealingUpdateAll
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleSoftmax0.01UpdateAll
#python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBayesianUpdateALl
python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBinomialUCIUpdateAll
#python create_mean_ensemble_bandit_proportions_vs_time_plot.py EnsembleBinomialUCIMod1UpdateAll
